---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5d42815ae17a550010437e7e/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Global site config
  templates:
  - config
- type: document
  path: index.md
  label: Home
  templates:
  - index
- type: document
  path: store.md
  label: Store
  templates:
  - store
- type: document
  path: faq.md
  label: FAQ
  templates:
  - faq
- type: document
  path: about.md
  label: About
  templates:
  - about
- type: directory
  path: categories
  label: Categories
  create: all
  match: "**/*"
  templates:
  - categories
- type: document
  path: _data/promotion.json
  label: Promotion
  templates:
  - promotion
- type: document
  path: _data/testimonials.json
  label: Testimonials
  templates:
  - testimonials
- type: directory
  path: products
  label: Product
  create: all
  match: "**/*"
  templates:
  - products
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
